### ISSUE TITLE
Rajouter le lien du site sur Github

### ISSUE THREAD

**Issue by guillaumebriday** [lyontechhub/lyontechhub.github.io#102]
Bonjour,

Est-il possible de rajouter le lien du site sur Github ? Je ne l'ai trouvé nul part sur le repo malheureusement.

Merci d'avance 🙏

**Comment by fpellet** [comment]
Bonjour,
Merci pour la remarque, c'est fait :)

**Comment by guillaumebriday** [comment]
Top merci !

C'est bien dans le readme aussi !

Mais je pensais surtout dans les infos du repos à côté du "Public web site that aggregates communication of group's communities."

Qu'en pensez-vous ?
