### ISSUE TITLE
Onglet Communauté vide

### ISSUE THREAD

**Issue by BoD** [lyontechhub/lyontechhub.github.io#109]
En allant sur le site ici : https://www.lyontechhub.org/#!/communautes , l'onglet est actuellement vide.

<img width="1167" alt="Screenshot 2023-06-09 at 13 24 35" src="https://github.com/lyontechhub/lyontechhub.github.io/assets/372852/0f8d77c7-e828-4ddc-83bb-41891fedecf1">

**Comment by blackheaven** [comment]
Merci, c'était moi :(

**Comment by fpellet** [comment]
corrigé, merci pour le signalement
