### ISSUE TITLE
Consentement utilisateur pour l'usage de Google Analytics (conformité CNIL)

### ISSUE THREAD

**Issue by devcrafting** [lyontechhub/lyontechhub.github.io#11]
Un code d'exemple est fourni ici, à intégrer avec Angulartics...
http://www.cnil.fr/vos-obligations/sites-web-cookies-et-autres-traceurs/outils-et-codes-sources/la-mesure-daudience/

**Comment by ubermuda** [comment]
Question : est-ce vraiment nécessaire d'avoir un Google Analytics ?

**Comment by devcrafting** [comment]
C sympa de savoir si le site est utile ou non, c'est sûr qu'on n'a pas besoin de tout GA...mais on pourrait se tourner vers un autre outil, genre Piwik qui semble "préconisé" par la CNIL (tutoriel de config fourni).

**Comment by fpellet** [comment]
tag supprimé
