### ISSUE TITLE
socialLinks et image des user groups non affichés

### ISSUE THREAD

**Issue by LouisCAD** [lyontechhub/lyontechhub.github.io#110]
Bonjour, les `socialLinks` et l'image ne sont pas affichés sur les pages des différents user groups.

Par exemple, pour le Lyon JUG :
- Données source : https://github.com/lyontechhub/lyontechhub.github.io/blob/dev/data/LyonJUG.json
- Résultat : https://www.lyontechhub.org/#!/communaute/LyonJUG

Possiblement lié aux changements qui ont mené à #109

**Comment by fpellet** [comment]
Merci pour le signalement 
C'est corrigé
