### ISSUE TITLE
logo en 512×512

### ISSUE THREAD

**Issue by cappert** [lyontechhub/lyontechhub.github.io#50]
![hub_512](https://cloud.githubusercontent.com/assets/71031/13285664/1e10f838-dafc-11e5-9f83-1eab37a64896.png)
(c) @woecifaun

**Comment by woecifaun** [comment]
Hi @cappert @jeantil 
I'll add it as SVG soon on this issue. It's on my personal computer at home.

By the way, I thought the lion with the mouth as curly brace was chosen… Just let me know which one I must upload.

**Comment by woecifaun** [comment]
Hi @cappert @jeantil 
I'll add it as SVG soon on this issue. It's on my personal computer at home.

By the way, I thought the lion with the mouth as curly brace was chosen… Just let me know which one I must upload.

**Comment by jeantil** [comment]
unfortunately the state of the consensus was lost from slack (it was beyond the 10k messages) so choose the one you like most :p

**Comment by jeantil** [comment]
and if you have the logo on a transparent background that would be awesome

**Comment by cappert** [comment]
fixed in #51
