### ISSUE TITLE
Mettre en place un déploiement continue GitHub -> Heroku

### ISSUE THREAD

**Issue by devcrafting** [lyontechhub/lyontechhub.github.io#8]
A regarder de plus près
https://github.com/himynameisjonas/heroku-deployer

**Comment by devcrafting** [comment]
HerokuDeployer ne gère que la branche master il me semble. On est sur la branche dev sur GitHub. Il faudrait donc modifier l'outil pour faire un git clone -b [branch] & git push heroku [branch]:master, une variable d'environnement est déjà prévue pour la branche à surveiller sur GitHub...

**Comment by michaelbaudino** [comment]
Pourquoi ne pas l'héberger sur Github:Pages directement ?

**Comment by devcrafting** [comment]
En fait, j'étais parti la-dessus, mais l'ayant fait en angularJS (certainement overkill je l'accorde, mais je me suis lancé pr découvrir et je n'avais pas la foi de recommencer pr faire plus simple), on n'avait pas de SEO.
Du coup, pour le SEO (c mieux pr un site vitrine), j'ai ajouté un petit serveur Node (server.js) qui intègre prerender.io. ghpages ne gère pas ça et je n'ai pas trouvé d'autres solutions simples pr rester sur ghpages. C t super simple à faire et à déployer sur heroku...

**Comment by devcrafting** [comment]
C fait via heroku-deployer, que j'ai très légèrement modifié (cf. https://github.com/lyontechhub/heroku-deployer). Tout est expliqué dans le README, c'est passé tout seul. J'ai juste simplifié en ne créant pas 2 comptes...le tout est fait avec un seul compte.
Et le mieux ça marche :) : un push déclenche la mise à jour sur heroku (quelques minutes de délai)
