### ISSUE TITLE
Wrong community event in Lyon Testing Community page

### ISSUE THREAD

**Issue by StephaneColson** [lyontechhub/lyontechhub.github.io#83]
Despite using different keywords, we can see a Lyon.rb event in the Lyon Testing community page.

<img width="865" alt="lyontechhub" src="https://user-images.githubusercontent.com/1481595/27014454-b323ca50-4ef9-11e7-9851-724d1948610e.png">

**Comment by fpellet** [comment]
Apparently, Google api search all text with this two words instead of the exact phrase :(

**Comment by StephaneColson** [comment]
Ok I understand, there's "Lyon" and "Testing" in the description of the next Lyon.rb event. A more robust version would be to search the exact phrase only in the title, right?

**Comment by StephaneColson** [comment]
How to fix this @fpellet Do you think about a workaround? We now have an AFUP event on our page: http://www.lyontechhub.org/#!/communaute/LyonTesting

**Comment by StephaneColson** [comment]
Merged, seems ok now on http://www.lyontechhub.org/#!/communaute/LyonTesting
